# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16a7ChItI7x-OCs_1wEAjdtqAZVjxqhNT
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="CJppwch5LaOhEHt0PX3w")
project = rf.workspace("30201220").project("beverage-containers-3atxb-vqovx-1ubgt")
version = project.version(1)
dataset = version.download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics

import ultralytics
ultralytics.checks()

!yolo task=detect mode=train model=yolov8s.pt data=/content/Beverage-Containers-1/data.yaml epochs=10 imgsz=640 batch=16 plots=True project=/content/drive/MyDrive/yolov8/train name=exp

!yolo task=detect mode=predict model=/content/drive/MyDrive/yolov8/train/exp/weights/best.pt data=/content/Beverage-Containers-1/data.yaml conf=0.25 imgsz=640 source=/content/Beverage-Containers-1/test/images imgsz=640

import glob
from IPython.display import Image, display
i=0
for imageNet in glob.glob('/content/Beverage-Containers-1/detect/exp/*.jpg'):
  print('\n')
  if i%5 ==0:
     display(Image(filename=imageNet))
     i+=1